#!/usr/bin/bash

# udev runs as root, so we need to tell it how to connect to the X server:
export DISPLAY=:0
export XAUTHORITY=/home/luiz/.Xauthority

sleep 5

conMonitor=$(xrandr| sed -n '/DP2 connected/p')
lidOpen=$(cat /proc/acpi/button/lid/LID0/state| sed -n '/open/p')

if [[ "$conMonitor" ]]; then
    if [[ "$lidOpen" ]]; then
        xrandr --output VIRTUAL1 --off --output eDP1 --mode 2880x1800 --pos 3840x0 --rotate normal --scale 2 --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --primary --mode 3840x2160 --pos 0x0 --rotate normal
    else
        xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --primary --mode 3840x2160 --pos 0x0 --rotate normal
        xbacklight -ctrl smc::kbd_backlight -set 0
    fi
else
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 2880x1800 --pos 0x0 --rotate normal --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
fi
